### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by KONTA2019** [KONTA2019/chat-space-kai#12]
#IPアドレス
13.112.68.204

**Comment by miyu-yamamoto** [comment]
今田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○ 新規チャットグループ作成のアイコンが見本通りではない**
**○ サイドバーのグループ、新規メッセージが一列で表示されている**
https://gyazo.com/d7b1c4d914ba3da4f35d576376bceb28

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by KONTA2019** [comment]
修正を行いましたのでご確認のほどよろしくお願いします

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by KONTA2019** [comment]
LGTMありがとうございます！
